---

platform: linux

image_resource:
  type: docker-image
  source: {repository: nsxedgegen/nsx-t-gen-worker}

params:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATACENTER:
  VCENTER_DATASTORE:
  VCENTER_CLUSTER:
  VCENTER_MANAGER:
  NTPSERVERS:
  MGMT_PORTGROUP:
  DNSSERVER:
  DNSDOMAIN:
  DEFAULTGATEWAY:
  NETMASK:
  ESXI_HOSTS_ROOT_PWD:
  ESXI_HOSTS_CONFIG:
  COMPUTE_VCENTER_HOST:
  COMPUTE_VCENTER_USR:
  COMPUTE_VCENTER_PWD:
  COMPUTE_VCENTER_CLUSTER:
  COMPUTE_VCENTER_MANAGER:
  NSX_T_MANAGER_FQDN:
  NSX_T_MANAGER_VM_NAME:
  NSX_T_MANAGER_HOST_NAME:
  NSX_T_MANAGER_IP:
  NSX_T_MANAGER_ADMIN_PWD:
  NSX_T_MANAGER_ROOT_PWD:
  NSX_T_CONTROLLER_HOST_PREFIX:
  NSX_T_CONTROLLER_VM_NAME_PREFIX:
  NSX_T_CONTROLLER_IPS:
  NSX_T_CONTROLLER_ROOT_PWD:
  NSX_T_CONTROLLER_CLUSTER_PWD:
  NSX_T_EDGE_HOST_PREFIX:
  NSX_T_EDGE_VM_NAME_PREFIX:
  NSX_T_EDGE_IPS:
  NSX_T_EDGE_ROOT_PWD:
  NSX_T_EDGE_PORTGROUP_EXT:
  NSX_T_EDGE_PORTGROUP_TRANSPORT:
  NSX_T_EDGE_OVERLAY_INTERFACE:
  NSX_T_EDGE_UPLINK_INTERFACE:
  NSX_T_MGR_DEPLOY_SIZE:
  NSX_T_EDGE_DEPLOY_SIZE:
  NSX_T_TEP_POOL_NAME:
  NSX_T_TEP_POOL_CIDR:
  NSX_T_TEP_POOL_GATEWAY:
  NSX_T_TEP_POOL_START:
  NSX_T_TEP_POOL_END:
  NSX_T_TEP_POOL_NAMESERVER:
  NSX_T_SINGLE_UPLINK_PROFILE_NAME:
  NSX_T_SINGLE_UPLINK_PROFILE_MTU:
  NSX_T_SINGLE_UPLINK_PROFILE_VLAN:
  NSX_T_EDGE_CLUSTER:
  NSX_T_KEEP_RESERVATION:
  NSX_T_OVERLAY_PROFILE_NAME:
  NSX_T_OVERLAY_PROFILE_MTU:
  NSX_T_OVERLAY_PROFILE_VLAN:
  NSX_T_ESXI_VMNICS:
  NSX_T_HOSTSWITCH:
  NSX_T_TRANSPORT_VLAN:
  NSX_T_T0ROUTER_SPEC:
  NSX_T_PAS_NCP_CLUSTER_TAG:
  NSX_T_OVERLAY_TRANSPORT_ZONE:
  NSX_T_VLAN_TRANSPORT_ZONE:
  NSX_T_HOSTSWITCH:
  NSX_T_T1ROUTER_LOGICAL_SWITCHES_SPEC:
  NSX_T_HA_SWITCHING_PROFILE_SPEC:
  NSX_T_CONTAINER_IP_BLOCK_SPEC:
  NSX_T_EXTERNAL_IP_POOL_SPEC:
  ENABLE_ANSIBLE_DEBUG:
  RERUN_CONFIGURE_CONTROLLERS:

    
inputs:
  - name: nsx-t-gen-pipeline
  - name: nsx-mgr-ova
  - name: nsx-ctrl-ova
  - name: nsx-edge-ova
  - name: nsxt-ansible
  - name: ovftool 

run:
  path: nsx-t-gen-pipeline/tasks/install-nsx-t/task.sh
